# Generated by Django 5.0.3 on 2024-03-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted'], 'verbose_name': 'All Post'},
        ),
        migrations.AddField(
            model_name='post',
            name='catagory',
            field=models.CharField(blank=True, choices=[('News', 'News'), ('Question', 'Question'), ('Tips', 'Tips'), ('Event', 'Event'), ('Other', 'Other')], max_length=100, null=True, verbose_name='catagory'),
        ),
        migrations.AlterField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True, verbose_name='public post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='posted date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posted_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sender_id',
            field=models.IntegerField(default=0, verbose_name='sender id'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sender_name',
            field=models.CharField(default='', max_length=100, verbose_name='sender name'),
        ),
    ]
