# Generated by Django 5.0.3 on 2024-03-15 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='date',
        ),
        migrations.AddField(
            model_name='test',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
