# Generated by Django 5.0.3 on 2024-03-15 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comment_delete_test_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
