# Generated by Django 5.0.3 on 2024-03-28 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField(default=1, verbose_name='sender id')),
                ('sender_name', models.CharField(default='', max_length=100, verbose_name='sender name')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='posted date')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
            ],
            options={
                'verbose_name': 'All Comment',
                'ordering': ['-date_posted'],
            },
        ),
    ]
