# Generated by Django 5.0.3 on 2024-04-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='posted_pdfs/%Y/%m/%d/', verbose_name='PDF file'),
        ),
    ]
