# Generated by Django 5.0.3 on 2024-04-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catagory',
            new_name='category',
        ),
    ]
