# Generated by Django 5.0.3 on 2024-05-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_rename_catagory_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('News', 'News'), ('Question', 'Question'), ('Tips', 'Tips'), ('Event', 'Event'), ('Other', 'Other')], max_length=100, null=True, verbose_name='category'),
        ),
    ]
