# Generated by Django 5.0.3 on 2024-05-05 12:18

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/male_def.jpg', upload_to=pages.models.user_directory_path),
        ),
    ]
