# Generated by Django 5.0.3 on 2024-03-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_login_password_alter_login_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='userid',
            new_name='username',
        ),
    ]
